### ISSUE TITLE
Compile also module dependants

### ISSUE THREAD

**Issue by domenkozar** [haskell/ghcide#216]
It seems like currently, ghcide will only typecheck open files, but that gives very often false positives.

It may seem like optimization, but it means I can't trust ghcide, so I have to manually compile the whole project before git commit.

**Comment by ocharles** [comment]
Can you say more why it's a false positive? How can something fail beyond type checking?

**Comment by cocreature** [comment]
It sounds like @domenkozar wants `ghcide` to typecheck module `B` which imports module `A` even if they have only opened `A`. I think that would be a reasonable feature but we might want to make it optional since on large projects loading everything can be quite expensive. I’m also not quite sure if we get enough information out of `hie-bios` to figure out which files are part of the current project.

**Comment by domenkozar** [comment]
Exactly. My workaround is to have `Main.hs` open all the time.

**Comment by ndmitchell** [comment]
I think to get this working we need slightly more info from hie-bios, namely the set of "root" modules, which need to be loaded in the background.

**Comment by domenkozar** [comment]
https://github.com/digital-asset/ghcide/pull/688

**Comment by jneira** [comment]
As #688 is already merged this can be closed
